paths:
  assetsDirectory: assets
  languageDirectory: assets/language
  minecraftDirectory: .minecraft
  objModelDirectory: assets/obj
  particlesConfigJson: assets/particles.json
  particlesJsonDirectory: assets/particles
  particlesTexturesDirectory: assets/particle
  pluginDirectory: plugins
  specialParticlesConfigJson: assets/special_particles.json
settings:
  LoadPluginMain: load_plugin.main
  debug: true
  installMinecraft: true
  language: zh_cn
  loadOtherPlugins: true
  logfilename: app.log
  logformat: '[%(levelname)s at %(filename)s %(asctime)s] %(message)s '
  recordinglog: false
  safeMode: true
  showDebugInfo: false
version: b0.1.0
